server:
  port: 8081

spring:
  application:
    name: mountain-man-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/mountain_man?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
    global-config:
      db-config:
        id-type: auto
        logic-delete-field: deleted
        logic-delete-value: 1
        logic-not-delete-value: 0
  
  thymeleaf:
    cache: false

logging:
  level:
    com.mountain: DEBUG